- name: Install aptitude
  apt: name=aptitude state=lateset force_apt_get=yes

- name: Upgrade all apt packages
  apt: upgrade-dist

- name: Create users
  user:
    name: john
    state: present
    shell: /bin/bash
    append: yes
- name: Create .ssh directory
  file:
    path: "/home/john/.ssh"
    state: directory
    owner: john
    group: john
    mode: "0755"

- name: Copy Public Key
  ansible.builtin.copy:
    src: /root/.ssh/authorized_keys
    dest: /home/john/.ssh/authorized_keys
    owner: john
    group: john
    mode: "0600"

- name: Install required packages
  apt:
    name:
      - fail2ban
      - htop
      - nginx
      - goaccess
      - mysql



- name: Set timezone to {{ timezone }}
  timezone:
    name: "{{ timezone }}"
- name: Disable root login over SSH
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present

- name: Disable password login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify:
    - restart sshd
